AWSTemplateFormatVersion: 2010-09-09
Description: A stack to store and alert user about crypto currencies.
Parameters:
  CoinList:
    Type: String
    Default: 'BTC,ETH'
  PctChangeCutoff:
    Type: Number
    Default: 5
  PhoneNumber:
    Type: String
    Default: 0
Resources:
  Alert:
    Properties:
      CodeUri: s3://my-test-bucket-drew/76b007ab8c02f74e216615f263d537ce
      Environment:
        Variables:
          COIN_LIST: !Ref CoinList
          PCT_CHANGE_CUTOFF: !Ref PctChangeCutoff
          PHONE_NUMBER: !Ref PhoneNumber
          SNS_TOPIC: !Ref SNSTopic
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        Timer:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: alert.lambda_handler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Runtime: python3.6
      Timeout: 60
    Type: AWS::Serverless::Function
    Metadata:
      StackeryName: Alert
  CollectPrices:
    Properties:
      CodeUri: s3://my-test-bucket-drew/76b007ab8c02f74e216615f263d537ce
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        Timer:
          Properties:
            Schedule: rate(5 minutes)
          Type: Schedule
      Handler: collect.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Runtime: python3.6
      Timeout: 60
    Type: AWS::Serverless::Function
    Metadata:
      StackeryName: CollectPrices
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: CoinId
          AttributeType: S
        - AttributeName: TimeStamp
          AttributeType: 'N'
      KeySchema:
        - AttributeName: CoinId
          KeyType: HASH
        - AttributeName: TimeStamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::DynamoDB::Table
    Metadata:
      StackeryName: DynamoDBTable
  SNSTopic:
    Properties:
      DisplayName: CryptoAlert
      Subscription:
        - Endpoint: !Ref PhoneNumber
          Protocol: sms
    Type: AWS::SNS::Topic
    Metadata:
      StackeryName: SNSTopic
Transform: AWS::Serverless-2016-10-31